class Constant:
	TRANSLATOR_REFERENCE = 'https://translate.yandex.net/api/v1.5/tr.json/translate'
	TRANSLATOR_API_KEY = 'trnsl.1.1.20200321T130137Z.ef5b35dd74f0ce01.173bcb1f6adb11f7fc34cae5cd75c6ecf2207261'
	TELEGRAM_API_KEY = '1074335244:AAE4XNOFBYavrLHb8xTR5g57TY_8XAaYjLs'  # @trn2Bot

	TITLE_RUS_ENG = 'Перевести на английски'
	TITLE_RUS_ESP = 'Перевести на испанский'
	TITLE_RUS_FRA = 'Перевести на французский'
	TITLE_ENG_RUS = 'Translate to Russian'
	TITLE_ENG_ESP = 'Translate to Spanish'
	TITLE_ENG_FRA = 'Translate to French'
	TITLE_ESP_ENG = 'Traducir al inglés'
	TITLE_ESP_RUS = 'Traducir al ruso'
	TITLE_ESP_FRA = 'Traducir al francés'
	TITLE_FRA_ENG = 'Traduire en anglais'
	TITLE_FRA_RUS = 'Traduire du russe'
	TITLE_FRA_ESP = 'Traduire en espagnol'

	DSCRP_RUS_ENG = '🇷🇺 ➡️ 🇬🇧'
	DSCRP_RUS_ESP = '🇷🇺 ➡️ 🇪🇸'
	DSCRP_RUS_FRA = '🇷🇺 ➡️ 🇫🇷'
	DSCRP_ENG_RUS = '🇬🇧 ➡️ 🇷🇺'
	DSCRP_ENG_ESP = '🇬🇧 ➡️ 🇪🇸'
	DSCRP_ENG_FRA = '🇬🇧 ➡️ 🇫🇷'
	DSCRP_ESP_ENG = '🇪🇸 ➡️ 🇬🇧'
	DSCRP_ESP_RUS = '🇪🇸 ➡️ 🇷🇺'
	DSCRP_ESP_FRA = '🇪🇸 ➡️ 🇫🇷'
	DSCRP_FRA_ENG = '🇫🇷 ➡️ 🇬🇧'
	DSCRP_FRA_RUS = '🇫🇷 ➡️ 🇷🇺'
	DSCRP_FRA_ESP = '🇫🇷 ➡️ 🇪🇸'

	FLAG_ENG = 'https://img.icons8.com/doodle/48/000000/great-britain.png'
	FLAG_RUS = 'https://img.icons8.com/doodle/48/000000/russian-federation.png'
	FLAG_ESP = 'https://img.icons8.com/doodle/48/000000/spain-2.png'
	FLAG_FRA = 'https://img.icons8.com/doodle/48/000000/france.png'

	RUS = 'ru'
	ENG = 'en'
	ESP = 'es'
	FRA = 'fr'

